# Generated by Django 5.0.14 on 2026-09-15 15:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncidentAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('submitted_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('emergency_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('avg_response_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_resolution_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_met_count', models.PositiveIntegerField(default=0)),
                ('sla_missed_count', models.PositiveIntegerField(default=0)),
                ('satisfaction_sum', models.PositiveIntegerField(default=0)),
                ('satisfaction_n', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
