# Generated by Django 5.0.14 on 2026-09-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincidentaggregate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='incidents.incidentcategory'),
        ),
        migrations.AddField(
            model_name='dailyincidentaggregate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='dailyincidentaggregate',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='core.ward'),
        ),
        migrations.AddConstraint(
            model_name='dailyincidentaggregate',
            constraint=models.UniqueConstraint(fields=('date', 'ward', 'category', 'department'), name='uniq_daily_aggregate'),
        ),
    ]
