# Generated by Django 5.0.14 on 2026-09-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaconfiguration',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Null = default rule for all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='incidents.incidentcategory'),
        ),
        migrations.AddField(
            model_name='ward',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='core.zone'),
        ),
        migrations.AddConstraint(
            model_name='slaconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('category', 'severity'), name='uniq_active_sla_category_severity'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['zone'], name='idx_ward_zone'),
        ),
    ]
