# Generated by Django 5.0.14 on 2026-09-20 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('incidents', '0003_incidentcomment_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = evaluated first')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('any', 'Any')], default='any', max_length=10)),
                ('statuses', models.JSONField(blank=True, default=list, help_text="List of status codes to trigger on, e.g. ['submitted', 'assigned']")),
                ('trigger_on_sla_breach', models.BooleanField(default=True)),
                ('trigger_after_hours', models.PositiveIntegerField(blank=True, help_text='Escalate after this many hours in matching status (regardless of SLA)', null=True)),
                ('trigger_on_reopen_count', models.PositiveIntegerField(blank=True, help_text='Escalate if reopened this many times', null=True)),
                ('escalate_to_level', models.CharField(choices=[('level_1', 'Level 1 — Supervisor'), ('level_2', 'Level 2 — Department Head'), ('level_3', 'Level 3 — Emergency Operations')], default='level_1', max_length=10)),
                ('notify_department_head', models.BooleanField(default=True)),
                ('auto_assign_supervisor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Null = all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='incidents.incidentcategory')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
