# Generated by Django 5.0.14 on 2026-09-15 15:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('category', 'Category suggestion'), ('severity', 'Severity suggestion'), ('priority', 'Priority recommendation'), ('duplicate', 'Duplicate similarity'), ('summary', 'Description summarization'), ('toxicity', 'Toxicity check'), ('translation', 'Translation'), ('entities', 'Entity extraction')], max_length=15)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('edited', 'Accepted with edits'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
