# Generated by Django 5.0.14 on 2026-09-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['kind'], name='idx_ai_kind'),
        ),
    ]
