# Generated by Django 5.0.14 on 2026-09-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_referencecounter_alter_incidentfeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcomment',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='incidents.incidentmedia'),
        ),
    ]
