# Generated by Django 5.0.14 on 2026-09-25 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_login_notifications_enabled_and_more'),
        ('core', '0003_escalationrule'),
        ('incidents', '0003_incidentcomment_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-created_at'], name='idx_incident_status_created'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reporter', '-created_at'], name='idx_incident_reporter_created'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['department', 'status', '-created_at'], name='idx_incident_dept_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['sla_breached', 'sla_deadline'], name='idx_incident_sla_state'),
        ),
    ]
