# Generated by Django 5.0.14 on 2026-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_login_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='false_report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reporting_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rejected_report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_blocked_reason',
            field=models.TextField(blank=True),
        ),
    ]
